@startuml class_diagram

hide circle
hide empty members
skinparam classAttributeIconSize 0

left to right direction

rectangle "Truth or Drink" {
    class Deck {
        + id : int
        + title : string
    }

    class Card {
        + id : int
        + question : string
        + deckId : int
    }
}

Card "1..n  " ---  "1  " Deck

@enduml