@startuml erd

hide circle
hide empty members
skinparam classAttributeIconSize 0

left to right direction

rectangle "Truth or Drink" {
    class Deck {
        id
        title
    }

    class Card {
        id
        question
        deckId
    }
}

Card }---  Deck

@enduml